### PR TITLE
Added support for adding a custom class on the counter container.

### LINKED ISSUE #10: Mind adding "counter_container_class" as an configuration option?
... it would make styling a lot easier, espacially when you have more than one counter.

      
      var defaults = {
        ...
        ...
        // Custom class for counter container
        counter_container_class: ''
      };
------------------------------------------------
      var methods = {
        init: function ($obj) {
          ...
          ...
          // Insert counter after or before text area/box
          $countObj = $("<span id=" + counterID + "/>");
          var counterDiv = $('<div/>')
            .attr('id', objID + '_counter')
            .addClass((options.counter_container_class && options.counter_container_class != '') ? options.counter_container_class : '')
            .append($countObj)
            .append(" " + methods.setMsg());

### PR DESCRIPTION
**Pull request by thomasgohard**
Fixes #10.

### CODE REVIEW

**Comment by thomasgohard** [comment]
@qwertypants how are you generating the minified version?

**Comment by qwertypants** [comment]
I never baked in a solution. I typically run it locally through command line using uglify.

**Comment by thomasgohard** [comment]
Do you use any particular options?

**Comment by qwertypants** [comment]
Just the default, nothing special.

**Pull request merged**
